---
title: "lab_8"
author: "Elizabeth, Zach, & Esmeralda"
date: "11/10/2021"
output: pdf_document
bibliography: lab_8.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 8, fig.width = 6.5)
```

## Commit 1
```{r}
library(tidyverse)
library(here)
library(rio)
library(janitor)
library (knitr)
library(tinytex)
# tinytex::install_tinytex()


data <- import(here("data", "star.csv"))
```


## Commit 2
```{r}

```
In this markdown, the following packages were used @tidyverse, @here, @rio, and @janitor

Some additional references were used to complete the requirements for this assignment: [@xu2020correlates], [@nebeling2020flashe], [@nebeling2017family], and [@nebeling2017flashe]

## Commit 3
```{r}
data %>%
  group_by(sex, frl) %>%
  summarize(math_mean = mean(tmathss), math_sd = sd(tmathss), rdg_mean = mean(treadss), rdg_sd = sd(treadss)) %>%
    kable(col.names= c("sex", "frl", "math_mean", "math_sd", "rdg_mean", "rdg_sd"), 
        digits = 2, 
        booktabs = FALSE)
  
```

## Commit 4
```{r}
data %>% 
  ggplot(aes(totexp, tmathss, fill = frl)) +
  geom_point(color = "grey") +
  geom_smooth(method = lm) +
  labs(x = "Teacher Experience (years)",
       y = "Total Math Scale Score",
       title = "Relation between Teacher Experience and Math Scores",
       subtitle = "Separate regression lines displayed by free/reduced price
       lunch status",
       fill = "Lunch status") +
  theme_minimal() +
  theme(legend.position = "bottom")
```



\newpage
# References